!
! FRRouting configuration for leaf2
! BGP peer to spine1
!
hostname leaf2
no ip forwarding
!
router bgp 65002
 bgp router-id 10.0.0.3
 bgp log-neighbor-changes
 neighbor spine1 remote-as 65000
 neighbor spine1 update-source 10.0.1.4
 !
 address-family ipv4 unicast
  neighbor spine1 activate
 exit-address-family
!
log syslog informational
log facility local0
!
interface eth1
 ip address 10.0.1.4/30
!
interface eth2
 ip address 10.0.2.2/30
!
