!
! FRRouting configuration for leaf1
! BGP peer to spine1
!
hostname leaf1
no ip forwarding
!
interface lo
 ip address 10.0.0.2/32
!
interface eth1
 ip address 10.0.1.2/30
!
interface eth2
 ip address 10.0.2.1/30
!
router bgp 65001
 bgp router-id 10.0.0.2
 bgp log-neighbor-changes
 neighbor 10.0.1.1 remote-as 65000
 neighbor 10.0.1.1 description spine1
 !
 address-family ipv4 unicast
  neighbor 10.0.1.1 activate
 exit-address-family
!
log syslog informational
log facility local0
!
