!
! FRRouting configuration for leaf2
! BGP peer to spine1
!
hostname leaf2
no ip forwarding
!
interface lo
 ip address 10.0.0.3/32
!
interface eth1
 ip address 10.0.1.6/30
!
interface eth2
 ip address 10.0.2.2/30
!
router bgp 65002
 bgp router-id 10.0.0.3
 bgp log-neighbor-changes
 neighbor 10.0.1.5 remote-as 65000
 neighbor 10.0.1.5 description spine1
 !
 address-family ipv4 unicast
  neighbor 10.0.1.5 activate
 exit-address-family
!
log syslog informational
log facility local0
!
